/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const customermessage_LogicpreprocessMessages = require('./code/customermessage-logicpreprocessMessages');

class xiaJiqiang_STUDENTG22Srv extends LCAPApplicationService {
    async init() {

        this.before('READ', 'CustomerMessage', async (request) => {
            await customermessage_LogicpreprocessMessages(request);
        });

        return super.init();
    }
}


module.exports = {
    xiaJiqiang_STUDENTG22Srv
};